config/routes.rb
Rails.application.routes.draw do
  resources :jokes, only: [:index] do
    member do
      patch :like, :dislike
    end
  end

  root 'jokes#index'
end

app/models/joke.rb
class Joke < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  before_action :set_joke, only: [:like, :dislike, :next_joke]

  def index
    if session[:out_of_joke] == true
      @joke = nil
    else
      @joke = Joke.first
    end
  end

  def like
    @joke.update_attribute(:like, @joke.like + 1)
    next_joke
  end

  def dislike
    @joke.update_attribute(:dislike, @joke.dislike + 1)
    next_joke
  end

  private

    def set_joke
      @joke = Joke.find(params[:id])
    end

    def next_joke
      
      # Checks last joke
      if @joke == last_joke
        session[:out_of_joke] ||= true
        @joke = nil
      else
        @joke = Joke.where('id > ?', @joke.id).first
      end

      render 'joke.js.erb'
    end

    def last_joke
      Joke.last
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/views/jokes/_joke.html.haml
.content
  %p= sanitize(joke.content)

= link_to "This is funny!", like_joke_path(joke), method: :patch, remote: true, class: "btn btn-primary btn-flat"
= link_to "This is not funny!", dislike_joke_path(joke), method: :patch, remote: true, class: "btn btn-success btn-flat"

app/views/jokes/index.html.haml
.container#main
  .row
    .col-md-8.col-md-offset-2
      #joke
        - if @joke.nil?
          %h3 That's all the jokes for today! Come back another day!
        - else
          = render @joke

app/views/jokes/joke.js.erb
<% if @joke.nil? %>
  $('#joke').html("<h3>That's all the jokes for today! Come back another day!</h3>");
<% else %>
  $('#joke').html('<%= escape_javascript render(@joke) %>');
<% end %>

app/views/layouts/_footer.html.haml
%footer
  %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt ducimus natus voluptate nulla inventore aliquam accusantium fugiat nostrum placeat libero cumque assumenda voluptates veniam mollitia eligendi perferendis molestiae harum repellendus omnis deleniti, odio odit sequi eaque alias. Voluptatum fugit, impedit et, unde tempore corrupti! Explicabo incidunt repellat at molestias assumenda.
  %p
    Copyright 2015 Futureworkz Ple. Ltd. 
    %strong Handcrafted by Joane Futureworkz

app/views/layouts/_header.html.haml
%header.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => "#menu", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only
          Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .logo
        = link_to image_tag("logo.jpg"), root_path, id: "logo"
    .navbar-collapse.collapse#menu
      %ul.nav.navbar-nav.navbar-right
        %li
          .info
            %p
              %i Handcrafted by
            %p
              %strong Joane Futureworkz
          .avt
            = image_tag "avt.jpg"

app/views/layouts/_intro.html.haml
#intro
  %h1 A joke a day keeps the doctor away 
  %h5 If you joke wrong way, your teeth have to pay (Session)

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Ta Minh Tien
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Lato:400,100,300,700,900,100italic,300italic,400italic,700italic,900italic'
  = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Muli:400,300,300italic,400italic'
  = csrf_meta_tags

%body
  = render 'layouts/header'
  = render 'layouts/intro'
  = yield
  = render 'layouts/footer'